### ISSUE TITLE
Right Click Issues

### ISSUE THREAD

**Issue by CRHarding** [CRHarding/Casino#1]
Figured a bit out, right clicking works when I don't have my Chrome inspector open...it doesn't work when I have the Chrome inspector open. I have no idea why, but if it's a bug with Chrome and not my code I'm fine with leaving it. I'm keeping this open in case it's something that I'm doing incorrectly with my code.

I've been trying to implement right clicking for flagging and it is not working. I've tried pretty much every method described that I've seen so it must be how I'm setting things up. The context menu still appears and the right click function is not called.

```
function createBoard(playerOne) {
	populateMines(playerOne);
	let grid = document.createElement('table');
	let gameBoard = document.getElementById('game-board');
	grid.className = 'grid';
	gameBoard.appendChild(grid);
	let elementArr = new Object(playerOne.size);
	for (let i = 0; i < playerOne.size; i++) {
		let tr = grid.appendChild(document.createElement('tr'));
		elementArr[i] = new Object(playerOne.size);
		for (let k = 0; k < playerOne.size; k++) {
			elementArr[i][k] = addSquare(i, k, tr, playerOne);
		}
	}

	playerOne.elementArr = elementArr;
}

function addSquare(i, k, tr, playerOne) {
	let cell = tr.appendChild(document.createElement('td'));
	let spaceElement = document.createElement('img');
	spaceElement.setAttribute('data-id', playerOne.mineArr[i][k].value);
	spaceElement.setAttribute('src', 'images/MinesweeperImages/Minesweeper_0.png');
	spaceElement.setAttribute('locX', i);
	spaceElement.setAttribute('locY', k);
	spaceElement.addEventListener('contextmenu', function() {event.preventDefault(); rightClick(event, playerOne)});
	spaceElement.addEventListener('mouseup', function() {clickFunction(event, playerOne)});
	cell.appendChild(spaceElement);
	return spaceElement;
}

function rightClick(e, playerOne) {
	document.getElementById('')
	console.log(e.target.matches('img'));
	if (e.target.matches('data-id *')) {
		e.stopPropagation();
		let xLoc = e.target.getAttribute('locX');
		let yLoc = e.target.getAttribute('locY');
		if (playerOne.mineArr[xLoc][yLoc].status != 'open') {
			playerOne.elementArr[xLoc][yLoc].setAttribute('src', 'images/MinesweeperiIages/Minesweeper_flagged.png');
		}
	}
	console.log('Right Click');
}
```

**Comment by jsm13** [comment]
I think the problem isn't that the right click function isn't running but that the mouse up event listener is also firing so you're seeing both happen. If I comment out the `mouseup` event and run your code, the context menu is suppressed and the logging in the `rightClick` callback does run.

**Comment by CRHarding** [comment]
It works if I don't have the inspector open, I didn't put my clickfunction code in but I have a check in the beginning that says 'if e.which !=3' to stop the right click from going through that. I don't understand why, if inspector is open, it doesn't let me override the contextmenu function. I just checked it now and flagged some squares, then opened inspector and tried to right click and the context menu popped up and the right click function didn't run. Hm.

**Comment by jsm13** [comment]
Yeah, that is strange. I'm not seeing the same behavior. I'll come to you
